export const detailedQuestions: string[] = [
  "Beach",
  "City",
  "Rainforest",
  "Mountain",
  "Strength",
  "Durability",
  "Repairability",
  "Prey Capture Ability",
  "Flexibility",
  "Biodegradability",
  "Camouflage",
  "Stickiness",
  "Visual Appeal: 5, Functionality: 0",
  "Visual Appeal: 4, Functionality: 1",
  "Visual Appeal: 3, Functionality: 2",
  "Visual Appeal: 2, Functionality: 3",
  "Visual Appeal: 1, Functionality: 4",
  "Visual Appeal: 0, Functionality: 5",
];

export const detailedPoints: { attributes: string[]; points: number[] }[] = [
  { attributes: ["patience, creativity"], points: [1, 1] },
  { attributes: ["communication, decision making"], points: [1, 1] },
  { attributes: ["adaptability, analytics"], points: [1, 1] },
  { attributes: ["independence, organization"], points: [1, 1] },
  { attributes: ["protectiveness"], points: [1] },
  { attributes: ["independence"], points: [1] },
  { attributes: ["problem solving"], points: [1] },
  { attributes: ["creativity"], points: [1] },
  { attributes: ["adaptability"], points: [1] },
  { attributes: ["ethics"], points: [1] },
  { attributes: ["analytics"], points: [1] },
  { attributes: ["patience"], points: [1] },
  { attributes: ["creativity, empathy"], points: [1, 1] },
  { attributes: ["teamwork, patience"], points: [1, 1] },
  { attributes: ["analytics, communication "], points: [1, 1] },
  { attributes: ["analytics, adaptability"], points: [1, 1] },
  { attributes: ["communication, independence"], points: [1, 1] },
  { attributes: ["decision making, organization, ethics"], points: [1, 1, 1] },
];
